# The URL the site will be built for
base_url = "https://ilikemac.com"
title = "I like Mac"
theme = "apollo" 

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feed = true
minify_html = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "auto" # light, dark, auto, toggle
comment = true

mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
  #{ name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
  #{ name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
  #{ name = "github", url = "https://github.com/donghao1393/", icon = "github" },
]

stylesheets = [
    "override.css",
    "something_else.css"
]

#[extra.analytics]
#enabled = false
#
#[extra.analytics.goatcounter]
#user = "your_user"
#host = "example.com"    # default= goatcounter.com
#
#[extra.analytics.umami]
#website_id = "43929cd1-1e83...."
#host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
